/**
 * SmileFile
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmileFile);
  }
}(this, function(expect, SmileFile) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmileFile.PatientVisitsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PatientVisitsInner', function() {
    it('should create an instance of PatientVisitsInner', function() {
      // uncomment below and update the code to test PatientVisitsInner
      //var instance = new SmileFile.PatientVisitsInner();
      //expect(instance).to.be.a(SmileFile.PatientVisitsInner);
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new SmileFile.PatientVisitsInner();
      //expect(instance).to.be();
    });

    it('should have the property diagnosis (base name: "diagnosis")', function() {
      // uncomment below and update the code to test the property diagnosis
      //var instance = new SmileFile.PatientVisitsInner();
      //expect(instance).to.be();
    });

    it('should have the property treatment (base name: "treatment")', function() {
      // uncomment below and update the code to test the property treatment
      //var instance = new SmileFile.PatientVisitsInner();
      //expect(instance).to.be();
    });

  });

}));
